# Generated by Django 2.2.1 on 2019-07-16 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='')),
                ('gender', models.CharField(choices=[('man', '남성'), ('woman', '여성')], max_length=10)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('find_id_question', models.CharField(max_length=50)),
                ('find_id_answer', models.CharField(max_length=20)),
                ('home_postcode', models.CharField(max_length=10)),
                ('home_roadAddress', models.CharField(max_length=100)),
                ('home_detailAddress', models.CharField(max_length=100)),
                ('high_school', models.CharField(max_length=20)),
                ('high_school_major', models.CharField(max_length=10)),
                ('high_school_dmission_year', models.CharField(blank=True, max_length=15)),
                ('high_school_graduation_year', models.CharField(blank=True, max_length=15)),
                ('university', models.CharField(max_length=20)),
                ('university_major', models.CharField(max_length=10)),
                ('university_dmission_year', models.CharField(blank=True, max_length=15)),
                ('university_graduation_year', models.CharField(blank=True, max_length=15)),
                ('graduate_school', models.CharField(max_length=20)),
                ('graduate_school_major', models.CharField(max_length=10)),
                ('graduate_school_dmission_year', models.CharField(blank=True, max_length=15)),
                ('graduate_school_graduation_year', models.CharField(blank=True, max_length=15)),
                ('qualification_division', models.CharField(choices=[('1', '사법연수원 수료자-공직 경력 없음'), ('2', '변호사 시험 합격자-공직 경력없음'), ('3', '판,검사'), ('4', '판,검사외 전 ,현직 모든 공직경력자 [재판 연구원, 경찰, 단기군법무관(법무관 병역 복무),공무원등]'), ('5', '군법무관')], max_length=5)),
                ('qualification_content', models.CharField(default='', max_length=50)),
                ('introduce', models.TextField()),
                ('rank', models.IntegerField(choices=[(0, '인증 대기 상태'), (1, '일반 변호사'), (2, '신뢰가는 변호사')], default=0)),
                ('rating', models.FloatField(default=0)),
                ('speciality', models.ManyToManyField(to='lawyerAccount.Speciality')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
