# Generated by Django 2.2.1 on 2019-07-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='keyVersion',
            field=models.CharField(default='0', max_length=8),
        ),
    ]
