# Generated by Django 2.2.1 on 2019-07-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerAccount', '0002_lawyer_keyversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='keyVersion',
            field=models.CharField(default='000000000', max_length=9),
        ),
    ]
