# Generated by Django 2.2.1 on 2019-07-25 07:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawyerAccount', '0001_initial'),
        ('helpline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatting_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='helpline.Author')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyerAccount.Lawyer')),
            ],
        ),
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helpline.Author')),
                ('lawyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyerAccount.Lawyer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatting.Chatting_room')),
            ],
        ),
    ]
