# Generated by Django 2.2.1 on 2019-07-16 01:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawyerAccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=108, verbose_name='이름')),
                ('identification_number', models.CharField(max_length=64, verbose_name='주민등록번호')),
                ('address', models.CharField(max_length=216, verbose_name='주소')),
                ('detail_address', models.CharField(max_length=216, verbose_name='거주지')),
                ('phone_number', models.CharField(max_length=64, verbose_name='연락처')),
                ('key', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='기관명')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unique_key', models.CharField(max_length=8, unique=True)),
                ('title', models.TextField(verbose_name='제목')),
                ('who', models.TextField(verbose_name='누가')),
                ('when', models.TextField(verbose_name='언제')),
                ('where', models.TextField(verbose_name='어디서')),
                ('content', models.TextField(verbose_name='내용')),
                ('witness', models.TextField(verbose_name='문제를 아는 사람')),
                ('method', models.TextField(verbose_name='문제 확인 방법')),
                ('grasp', models.CharField(max_length=108, verbose_name='파악 경위')),
                ('term', models.CharField(max_length=64, verbose_name='기간')),
                ('password', models.CharField(max_length=32, verbose_name='비밀번호')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lawyer_ack_date', models.DateField(blank=True, null=True)),
                ('lawyer_ack', models.CharField(choices=[('1', '승인 대기 중'), ('2', '승인'), ('3', '거절')], default='1', max_length=1, verbose_name='수임 여부')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='helpline.Author', verbose_name='신고자')),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyerAccount.Lawyer', verbose_name='변호사')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpline.Organization', verbose_name='기관명')),
            ],
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='helpline/report/%Y/%m/%d', verbose_name='첨부파일')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpline.Report', verbose_name='신고서')),
            ],
        ),
    ]
