# Generated by Django 2.2.1 on 2019-07-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0002_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='lawyer_refuse_msg',
            field=models.TextField(blank=True, null=True, verbose_name='거절 사유'),
        ),
    ]
